### PR TITLE
update punjabi language translation

### PR DESCRIPTION
**Pull request by ShareASmile**
This PR updates values-pa 'punjabi' language strings to make up-to-date with current dev having added new strings

Also added punjabi to fastlane description

### CODE REVIEW

**Comment by ShareASmile** [comment]
@z-huang build failure report does not represent a thoroughly helpful message or i ican't interpret it meaningfully, sorry. Need your help.

**Comment by z-huang** [comment]
Please sync to the latest commit.

**Comment by ShareASmile** [comment]
done & build succeeds

**Comment by z-huang** [comment]
Thanks!

**Pull request merged**
