### PR TITLE
Update German Language

### PR DESCRIPTION
**Pull request by siggi1984**

### CODE REVIEW

**Comment by siggi1984** [comment]
oy what did i do wrong?

**Comment by javdc** [comment]
> oy what did i do wrong?

In line 222 you forgot a `<` when closing the string

**Comment by siggi1984** [comment]
> > oy what did i do wrong?
> 
> In line 222 you forgot a `<` when closing the string

thank you, will try it again right away

**Comment by z-huang** [comment]
Thanks!

**Pull request merged**
